// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package easyjson

import (
	json "encoding/json"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
)

func easyjson8d5c760DecodeGithubComRedstoneFinanceRedstoneContractsWasmGoEasyjson(in *jlexer.Lexer, out *PstStateEs) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ticker":
			out.Ticker = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "owner":
			out.Owner = string(in.String())
		case "evolve":
			out.Evolve = string(in.String())
		case "canEvolve":
			out.CanEvolve = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8d5c760EncodeGithubComRedstoneFinanceRedstoneContractsWasmGoEasyjson(out *jwriter.Writer, in PstStateEs) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ticker\":"
		out.RawString(prefix[1:])
		out.String(string(in.Ticker))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"owner\":"
		out.RawString(prefix)
		out.String(string(in.Owner))
	}
	{
		const prefix string = ",\"evolve\":"
		out.RawString(prefix)
		out.String(string(in.Evolve))
	}
	{
		const prefix string = ",\"canEvolve\":"
		out.RawString(prefix)
		out.Bool(bool(in.CanEvolve))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PstStateEs) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8d5c760EncodeGithubComRedstoneFinanceRedstoneContractsWasmGoEasyjson(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PstStateEs) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8d5c760EncodeGithubComRedstoneFinanceRedstoneContractsWasmGoEasyjson(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PstStateEs) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8d5c760DecodeGithubComRedstoneFinanceRedstoneContractsWasmGoEasyjson(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PstStateEs) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8d5c760DecodeGithubComRedstoneFinanceRedstoneContractsWasmGoEasyjson(l, v)
}
